language: ruby
cache: bundler
os: linux

script:
  - bundle install
  - rake clean
  - rake build

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  skip_cleanup: true
  local_dir: '_site'
  fqdn: www.areweinspaceyet.org
  on:
    branch: master
